name: Code Quality

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './src ./include'
        extensions: 'h,cpp'
        clangFormatVersion: 12

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --std=c++20 ./src ./include
