name: DCO Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: linuxfoundation/dco@v1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
